Repository thestrangetoolstore/nodenogg.in, pull requests merged in 2025-07, with the labels that each got.

#45 docs: improves usage instructions
  README.md
Labels: documentation

#59 fix: edited changelog config
  changelog.config.json
Labels: bug

#76 Feature/UI improvements
  packages/spatial-view/src/SpatialView.vue
  products/app/src/components/EmptyState.vue
  products/app/src/components/ViewContainer.vue
  products/app/src/components/editor/Editor.vue
  products/app/src/components/entity/HTMLEntity.vue
  products/app/src/components/footer/Footer.vue
  products/app/src/components/menu/AppMenu.vue
  products/app/src/components/menu/JoinMicrocosmDialog.vue
  products/app/src/constants/copy.ts
  products/app/src/css/typography.css
  products/app/src/routes/index.route.vue
  products/app/src/views/collect/CollectNode.vue
  products/app/src/views/collect/MicrocosmCollectView.vue
  products/app/src/views/spatial/components/ZoomControls.vue
Labels: bug, enhancement

#86 Feat/manual release
  .github/workflows/release.yml
  packages/y-microcosm/src/YMicrocosmAPI.ts
  products/app/src/components/IdentityCount.vue
  products/app/src/components/editor/Editor.vue
  products/app/src/components/menu/AppMenu.vue
  products/app/src/components/menu/JoinMicrocosmDialog.vue
Labels: enhancement
